name: funrobo
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - tk
  - ipython
  - opencv
  - matplotlib
  - numpy
  - pygame
  - scipy
  - pyyaml
  - pytest
  - pynput
  - pip:
      - -e .
